local:
    api_base: "http://localhost:11434/v1"
    api_key: "EMPTY"

stepfun:
    api_base: "https://api.stepfun.com/v1/"
    api_key: "EMPTY"

luminaut:
    api_base: "https://kapi.stepfun.com/v1/"
    api_key: "EMPTY"
    uid: "EMPTY"